site_name: VJMotion library for Processing
site_url: "https://vincentsijben.github.io/vjmotion-processing/"

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: MIT Licence.

plugins:
  - search
  - offline

nav:
  - Home: index.md
  - Get Started: getting-started.md
  - BPM: bpm.md
  - Arduino Controls: arduinocontrols.md
  - Frequency Analyzer: frequencyanalyzer.md
  - Contribute: contribute.md
